name: ios

on: [push, pull_request]

jobs:
  build:
    name: Build - IOS
    runs-on: macOS-latest
    strategy:
      matrix:
        target:
          - aarch64-apple-ios

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Check
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: check
        args: --target=${{ matrix.target }}
